/*****************************************************************************
   can_533__0004.h
   Generated By:
   Raptor 2023b_1.0.0 (9999_9999)
   Matlab (R2023a) 9.14

   Copyright (c) 2024 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Wed Mar 27 13:31:34 2024
 *****************************************************************************/

#ifndef __CAN_533__0004_H
#define __CAN_533__0004_H

/*  CAN Bus: CAN3_LOCAL */
/*  Resource: CAN3 */
#include "Can.h"

/* FUNCTION PROTOTYPES */
/* CAN initialization */
extern void pre_start_CAN_533__0004(void);
extern void post_start_CAN_533__0004(void);

/* Receive CAN object declarations */

/* Transmit CAN object declarations */
#endif
