/*****************************************************************************
   can_531__0004.h
   Generated By:
   Raptor 2023b_1.0.0 (9999_9999)
   Matlab (R2023a) 9.14

   Copyright (c) 2024 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Wed Mar 27 13:31:34 2024
 *****************************************************************************/

#ifndef __CAN_531__0004_H
#define __CAN_531__0004_H

/*  CAN Bus: CAN1 */
/*  Resource: CAN1 */
#include "Can.h"

/* FUNCTION PROTOTYPES */
/* CAN initialization */
extern void pre_start_CAN_531__0004(void);
extern void post_start_CAN_531__0004(void);

/* Receive CAN object declarations */
extern uint32_T RxTrig_XCP_BC_XCP1_msgID;
extern uint8_T RxTrig_XCP_BC_XCP1_msgExtended;
extern uint8_T can_get_RxTrig_XCP_BC_XCP1(uint16_T *age, uint32_T* id, uint8_T
  * extended, uint8_T *data, uint8_T length);

//extern void RxTrig_XCP_BC_XCP1();
extern uint32_T RxTrig_XCP_CMD_XCP1_msgID;
extern uint8_T RxTrig_XCP_CMD_XCP1_msgExtended;
extern uint8_T can_get_RxTrig_XCP_CMD_XCP1(uint16_T *age, uint32_T* id, uint8_T*
  extended, uint8_T *data, uint8_T length);

//extern void RxTrig_XCP_CMD_XCP1();
extern uint8_T can_get_uds_receive(uint16_T *age, uint32_T* id, uint8_T
  * extended, uint8_T *data, uint8_T length);

//extern void uds_request_trigger();

/* Transmit CAN object declarations */
extern void can_send_Tx_XCP_XCP1(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);
extern void can_send_uds_send(uint32_T id, uint8_T extended, uint8_T length,
  const uint8_T *data);

#endif
