/*****************************************************************************
   data_api.h
   Generated By:
   Raptor 2023b_1.0.0 (9999_9999)
   Matlab (R2023a) 9.14

   Copyright (c) 2024 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Wed Mar 27 13:31:34 2024
 *****************************************************************************/

#ifndef DATA_API_H_
#define DATA_API_H_

extern void App_EE_WriteAsync(uint8 param);
extern void App_FEE_WriteAsync(uint8 param);

#endif                                 /* DATA_API_H_ */
