/*****************************************************************************
   L9945_raptor_cfg.c
   Generated By:
   Raptor 2023b_1.0.0 (9999_9999)
   Matlab (R2023a) 9.14

   Copyright (c) 2024 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Wed Mar 27 13:31:34 2024
 *****************************************************************************/

#include "Spi_Cfg.h"
#include "L9945_cfg.h"
#if(BIOS_L9945_USED == STD_ON)

const tL9945InstanceCofig cL9945Instances[BIOS_NUM_L9945_INSTANCES] = {
  /* L9945_INSTANCE_HSO1_8 */
  {
    BIOS_DSPI_L9945TR_HSO1_8,

    { 0x02000000 },                    /*      REG0 Enable Diagnostics    */

    { L9945_CHANNEL_DEACTIVATED_2202 },/*         REG1    */

    { L9945_CHANNEL_DEACTIVATED_2202 },/*         REG2    */

    { L9945_CHANNEL_DEACTIVATED_2202 },/*         REG3    */

    { L9945_CHANNEL_DEACTIVATED_2202 },/*         REG4    */

    { L9945_CHANNEL_DEACTIVATED_2202 },/*         REG5    */

    { L9945_CHANNEL_DEACTIVATED_2202 },/*         REG6    */

    { L9945_CHANNEL_DEACTIVATED_2202 },/*         REG7    */

    { L9945_CHANNEL_DEACTIVATED_2202 },/*         REG8    */

    { 0x00000000 },                    /*         REG9    */

    { 0x00000008 },                    /*        REG10    */
  },

  /* L9945_INSTANCE_HSO9_16 */
  {
    BIOS_DSPI_L9945TR_HSO9_16,

    { 0x02000000 },                    /*      REG0 Enable Diagnostics    */

    { L9945_CHANNEL_DEACTIVATED_2202 },/*         REG1    */

    { L9945_CHANNEL_DEACTIVATED_2202 },/*         REG2    */

    { L9945_CHANNEL_DEACTIVATED_2202 },/*         REG3    */

    { L9945_CHANNEL_DEACTIVATED_2202 },/*         REG4    */

    { L9945_CHANNEL_DEACTIVATED_2202 },/*         REG5    */

    { L9945_CHANNEL_DEACTIVATED_2202 },/*         REG6    */

    { L9945_CHANNEL_DEACTIVATED_2202 },/*         REG7    */

    { L9945_CHANNEL_DEACTIVATED_2202 },/*         REG8    */

    { 0x00000000 },                    /*         REG9    */

    { 0x00000008 },                    /*        REG10    */
  },

  /* L9945_INSTANCE_HBRIDGE */
  {
    BIOS_DSPI_L9945TR_HBRIDGE,

    { 0x02000000 },                    /*      REG0 Enable Diagnostics    */

    { L9945_CHANNEL_DEACTIVATED_2202 },/*         REG1    */

    { L9945_CHANNEL_DEACTIVATED_2202 },/*         REG2    */

    { L9945_CHANNEL_DEACTIVATED_2202 },/*         REG3    */

    { L9945_CHANNEL_DEACTIVATED_2202 },/*         REG4    */

    { L9945_CHANNEL_DEACTIVATED_2202 },/*         REG5    */

    { L9945_CHANNEL_DEACTIVATED_2202 },/*         REG6    */

    { L9945_CHANNEL_DEACTIVATED_2202 },/*         REG7    */

    { L9945_CHANNEL_DEACTIVATED_2202 },/*         REG8    */

    { 0x00000000 },                    /*         REG9    */

    { 0x00000008 },                    /*        REG10    */
  },

  /* L9945_INSTANCE_LSO1_8 */
  {
    BIOS_DSPI_L9945TR_LSO1_8,

    { 0x02000000 },                    /*      REG0 Enable Diagnostics    */

    { L9945_CHANNEL_DEACTIVATED_2202 },/*         REG1    */

    { L9945_CHANNEL_DEACTIVATED_2202 },/*         REG2    */

    { L9945_CHANNEL_DEACTIVATED_2202 },/*         REG3    */

    { L9945_CHANNEL_DEACTIVATED_2202 },/*         REG4    */

    { L9945_CHANNEL_DEACTIVATED_2202 },/*         REG5    */

    { L9945_CHANNEL_DEACTIVATED_2202 },/*         REG6    */

    { L9945_CHANNEL_DEACTIVATED_2202 },/*         REG7    */

    { L9945_CHANNEL_DEACTIVATED_2202 },/*         REG8    */

    { 0x00000000 },                    /*         REG9    */

    { 0x00000008 },                    /*        REG10    */
  },

  /* L9945_INSTANCE_LSO9_16 */
  {
    BIOS_DSPI_L9945TR_LSO9_16,

    { 0x02000000 },                    /*      REG0 Enable Diagnostics    */

    { L9945_CHANNEL_DEACTIVATED_2202 },/*         REG1    */

    { L9945_CHANNEL_DEACTIVATED_2202 },/*         REG2    */

    { L9945_CHANNEL_DEACTIVATED_2202 },/*         REG3    */

    { L9945_CHANNEL_DEACTIVATED_2202 },/*         REG4    */

    { L9945_CHANNEL_DEACTIVATED_2202 },/*         REG5    */

    { L9945_CHANNEL_DEACTIVATED_2202 },/*         REG6    */

    { L9945_CHANNEL_DEACTIVATED_2202 },/*         REG7    */

    { L9945_CHANNEL_DEACTIVATED_2202 },/*         REG8    */

    { 0x00000000 },                    /*         REG9    */

    { 0x00000008 },                    /*        REG10    */
  },
};

#endif                                 // BIOS_L9945_USED == STD_ON
