/*****************************************************************************
   Lin_Cfg.h
   Generated By:
   Raptor 2023b_1.0.0 (9999_9999)
   Matlab (R2023a) 9.14

   Copyright (c) 2024 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Wed Mar 27 13:31:34 2024
 *****************************************************************************/

#ifndef LIN_CFG_H_
#define LIN_CFG_H_

/*=====================================================================================================================
   Includes
   ====================================================================================================================*/
/*=====================================================================================================================
   Important Definitions
   ====================================================================================================================*/
/** Total frame in the channel 0 */
#define BIOS_LIN_NO_FLAG_PER_ELEMENT   (32U)
#define BIOS_LIN_APPEND_FLAG(x)        (((uint8)0x01U)<<(x % BIOS_LIN_NO_FLAG_PER_ELEMENT))

/*====================================================================================================================
   External Definitions
   ====================================================================================================================*/
extern const tBiosLinNodeConfig bios_Lin_ClustersConfig[BIOS_LIN_TOTAL_CHNL];
extern volatile struct LINFLEXD_tag * bios_Lin_registerBase[BIOS_LIN_TOTAL_CHNL];
extern const tBiosLinSchedTableMap bios_Lin_SchTableMap[BIOS_LIN_TOTAL_CHNL];
extern const tBiosLinFrameTable const bios_Lin_FrameTables[BIOS_LIN_TOTAL_CHNL];

#endif                                 /* LIN_CFG_H_ */
