/*****************************************************************************
   platform_api.h
   Generated By:
   Raptor 2023b_1.0.0 (9999_9999)
   Matlab (R2023a) 9.14

   Copyright (c) 2024 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Wed Mar 27 13:31:34 2024
 *****************************************************************************/

#ifndef PLATFORM_API_H
#define PLATFORM_API_H
#ifndef HIGHTEC
#include <errno.h>
#include "stdio.h"
#endif

#include "raptor_types.h"
#ifdef HIGHTEC

void memcpy(void *dest, const void * src, uint16_T n);
void memset(void *dest, uint8_T value, uint16_T n);
uint16_T memcmp(const void *data1, const void *data2, uint16_T n);

#endif
#endif
