/*****************************************************************************
   platform.c
   Generated By:
   Raptor 2023b_1.0.0 (9999_9999)
   Matlab (R2023a) 9.14

   Copyright (c) 2024 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Wed Mar 27 13:31:34 2024
 *****************************************************************************/

#include "platform_api.h"
#ifdef HIGHTEC

void memcpy ( void *dest, const void * src, uint16_T n)
{
  const uint8_T* source = (const uint8_T *)src;
  uint8_T* dst = (uint8_T *)dest;
  uint16_T len = n;
  while (len-- > 0U) {
    *dst = *source;
    dst++;
    source++;
  }
}

void memset(void *dest, uint8_T value, uint16_T n)
{
  uint8_T* dst = (uint8_T *)dest;
  uint16_T len = n;
  while (len-- > 0U) {
    *dst = value;
    dst++;
  }
}

uint16_T memcmp(const void *data1, const void *data2, uint16_T n)
{
  const uint8_T* d1 = (const uint8_T *)data1;
  const uint8_T* d2 = (const uint8_T *)data2;
  uint16_T len = n;
  uint16_T ret = 0;
  while (len-- > 0U) {
    if (*d1++ != *d2++) {
      ret = d1[-1] < d2[-1] ? -1 : 1;
      break;
    }
  }

  return ret;
}

#endif
