/*****************************************************************************
   raptor_gen.c
   Generated By:
   Raptor 2023b_1.0.0 (9999_9999)
   Matlab (R2023a) 9.14

   Copyright (c) 2024 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Wed Mar 27 13:31:34 2024
 *****************************************************************************/

#include "rcm112_stack_check.h"
#include "rcm112_stack_check_private.h"
#include "bootmailbox.h"
#include "raptor_gen.h"
#include "interface.h"
#include "data_api.h"
#include "Dio.h"
#include "CanTrcv_api.h"
#include "L9945_api.h"

/*****************************************************************************
   DEFINES
 *****************************************************************************/
#define TIMESUB(A,B)                   ((A >= B) ? (A-B):(0xFFFFFFFF-B+1+A))

/*****************************************************************************
   CONSTANTS
 *****************************************************************************/
uint8 app_is_in_shutdown = 0;
uint8 g_Reprogram_Requested = 0;
uint8 g_Sleep_Requested = 0;
uint8 g_EEWrite_Requested = 0;

/*****************************************************************************
   CAN PARTIAL NETWORKING DEFINITONS
 *****************************************************************************/
const tBiosCanTrcvSwkCfg bios_CanTrcv_TLE9255_SWK_cfg = {
  FALSE,
  0x7FFU,
  0x7FFU,
  8,
  0x0000000000000000U,
};

const tBiosCanTrcvCfgType bios_CanTrcv_SetUpCfg[BIOS_CANTRCV_TOTAL_IDX] = {
  {
    BIOS_CANTRCV_BR_500KB,
    BIOS_CANTRCV_NORMAL_MODE,
    BIOS_CANTRCV_SELECTIVE_WU,
  }
};

/*****************************************************************************
   STATIC FUNCTIONS
 *****************************************************************************/
static void APP_Report_Reset_Condition(tBiosCoreID offendingCore, tBiosTaskID
  offendingTask, uint16 ErrorCode);

/*****************************************************************************
   EXTERNAL FUNCTIONS
 *****************************************************************************/
extern uint32 Bios_Rtos_MC0GetFreerun (void);
extern boolean Bios_Rtos_HasTimeExpired (uint32 newTime, uint32 referenceTime,
  uint32 expirationPeriod);

/*****************************************************************************
   TIMER CALLBACK FUNCTIONS
 *****************************************************************************/
BootMailBox_t bootmailbox __attribute__ ((section (".bootmailbox"))) =
{
  0,

  { 0, 0, 0, 0, 0, 0, 0, 0 },
  0xCAFE,
};

tBiosProtectionHookAction App_Rtos_ProtectionHook (
  tBiosProtectionHookSource whichError,
  tBiosProtectionHookAction recommendedAction,
  tBiosCoreID whichCore,
  tBiosTaskID whichTask,
  uint32 payloadData)
{
  APP_Report_Reset_Condition(whichCore, whichTask, whichError);
  return (BIOS_RTOS_PROSHUTDOWN);
}

tBiosErrorHookAction App_Rtos_ErrorHook (tBiosErrorHookSource whichError,
  tBiosErrorHookAction recommendedAction,
  tBiosCoreID whichCore,
  tBiosTaskID whichTask,
  uint32 offendingService)
{
  APP_Report_Reset_Condition(whichCore, whichTask, (whichError + 16));
  return (BIOS_RTOS_ERRSHUTDOWN);
}

static void APP_Report_Reset_Condition(tBiosCoreID offendingCore, tBiosTaskID
  offendingTask, uint16 ErrorCode)
{
  uint8 writeBuffer[EEE_PAGE_SIZE] = { 0 };

  if (Bios_Fee_Page0.resetCause != ErrorCode || Bios_Fee_Page0.resetTask !=
      offendingTask) {
    Bios_Fee_Page0.resetCause = ErrorCode;
    Bios_Fee_Page0.ResetHist[9] = Bios_Fee_Page0.ResetHist[8];
    Bios_Fee_Page0.ResetHist[8] = Bios_Fee_Page0.ResetHist[7];
    Bios_Fee_Page0.ResetHist[7] = Bios_Fee_Page0.ResetHist[6];
    Bios_Fee_Page0.ResetHist[6] = Bios_Fee_Page0.ResetHist[5];
    Bios_Fee_Page0.ResetHist[5] = Bios_Fee_Page0.ResetHist[4];
    Bios_Fee_Page0.ResetHist[4] = Bios_Fee_Page0.ResetHist[3];
    Bios_Fee_Page0.ResetHist[3] = Bios_Fee_Page0.ResetHist[2];
    Bios_Fee_Page0.ResetHist[2] = Bios_Fee_Page0.ResetHist[1];
    Bios_Fee_Page0.ResetHist[1] = Bios_Fee_Page0.ResetHist[0];
    Bios_Fee_Page0.ResetHist[0] = ErrorCode;
    Bios_Fee_Page0.resetTask = offendingTask;
    Bios_Fee_Page0.ResetTaskHist[9] = Bios_Fee_Page0.ResetHist[8];
    Bios_Fee_Page0.ResetTaskHist[8] = Bios_Fee_Page0.ResetHist[7];
    Bios_Fee_Page0.ResetTaskHist[7] = Bios_Fee_Page0.ResetHist[6];
    Bios_Fee_Page0.ResetTaskHist[6] = Bios_Fee_Page0.ResetHist[5];
    Bios_Fee_Page0.ResetTaskHist[5] = Bios_Fee_Page0.ResetHist[4];
    Bios_Fee_Page0.ResetTaskHist[4] = Bios_Fee_Page0.ResetHist[3];
    Bios_Fee_Page0.ResetTaskHist[3] = Bios_Fee_Page0.ResetHist[2];
    Bios_Fee_Page0.ResetTaskHist[2] = Bios_Fee_Page0.ResetHist[1];
    Bios_Fee_Page0.ResetTaskHist[1] = Bios_Fee_Page0.ResetHist[0];
    Bios_Fee_Page0.ResetTaskHist[0] = offendingTask;
    Bios_Fee_Page0.Fill = 0x0000;
    memcpy(&writeBuffer, &Bios_Fee_Page0, sizeof(tBiosFeePage0));
    Bios_Fee_WriteNvData(0, &writeBuffer, EEE_PAGE_SIZE);
  }
}

/*****************************************************************************
   APPLICATION CALLBACK FUNCTIONS
 *****************************************************************************/
void App_Startup(void)
{
  Bios_CanTrcv_SetMode (BIOS_CANTRCV_TLE9255_IDX, BIOS_CANTRCV_NORMAL_MODE);
  app_is_in_shutdown = 0;
}

void App_Shutdown(void)
{
  app_is_in_shutdown = 1;
}

void App_Core0Idle(void)
{
}

#ifdef GCCFREE

extern uint8_T AppDescriptor;
uint8_T *tmpAppdesc = &AppDescriptor;

#endif

void App_Rtos_MC0HardwareInitHook(void)
{
  initRAMVariables(&RAMVariables);
  initCONSTVariables(&CONSTVariables);

  {
    extern void App_EE_Init(void);
    App_EE_Init();
  }

  rcm112_stack_check_initialize();
  App_Startup();

  /* CAN Bus Initializations */
  pre_start_CAN_531__0004();           /* <Root>/raptor_can_def */
  pre_start_CAN_532__0004();           /* <Root>/raptor_can_def1 */
  pre_start_CAN_533__0004();           /* <Root>/raptor_can_def2 */
  pre_start_CAN_534__0004();           /* <Root>/raptor_can_def3 */
  pre_start_CAN_535__0004();           /* <Root>/raptor_can_def4 */
  post_start_CAN_531__0004();          /* <Root>/raptor_can_def */
  post_start_CAN_532__0004();          /* <Root>/raptor_can_def1 */
  post_start_CAN_533__0004();          /* <Root>/raptor_can_def2 */
  post_start_CAN_534__0004();          /* <Root>/raptor_can_def3 */
  post_start_CAN_535__0004();          /* <Root>/raptor_can_def4 */
  Xcp_Initialize();
  Bios_Dio_SetOutputLevel(LIN2_EN, STD_HIGH);
}

Std_ReturnType Module_Shutdown(boolean_T shutdownPower)
{
  if (shutdownPower) {
    g_Sleep_Requested = 1;
    return E_OK;
  } else {             /* Shutdown, but requesting to skip the powerdown step */
    Bios_Mcu_TriggerReset();
    return E_OK;
  }
}

Std_ReturnType Module_BootRequest(void)
{
  g_Reprogram_Requested = 0x1;
}

void App_Disable_Power_Outputs (void)
{
  Bios_Pwm_Set (LSO_1_M, (uint16)0, (uint32)0);
  Bios_Pwm_Set (LSO_2_M, (uint16)0, (uint32)0);
  Bios_Pwm_Set (LSO_3_M, (uint16)0, (uint32)0);
  Bios_Pwm_Set (LSO_4_M, (uint16)0, (uint32)0);
  Bios_Pwm_Set (LSO_5_M, (uint16)0, (uint32)0);
  Bios_Pwm_Set (LSO_6_M, (uint16)0, (uint32)0);
  Bios_Pwm_Set (LSO_7_M, (uint16)0, (uint32)0);
  Bios_Pwm_Set (LSO_8_M, (uint16)0, (uint32)0);
  Bios_Pwm_Set (LSO_9_M, (uint16)0, (uint32)0);
  Bios_Pwm_Set (LSO_10_M, (uint16)0, (uint32)0);
  Bios_Pwm_Set (LSO_11_M, (uint16)0, (uint32)0);
  Bios_Pwm_Set (LSO_12_M, (uint16)0, (uint32)0);
  Bios_Pwm_Set (LSO_13_M, (uint16)0, (uint32)0);
  Bios_Pwm_Set (LSO_14_M, (uint16)0, (uint32)0);
  Bios_Pwm_Set (LSO_15_M, (uint16)0, (uint32)0);
  Bios_Pwm_Set (LSO_16_M, (uint16)0, (uint32)0);
  Bios_Pwm_Set (HSO_1_M, (uint16)0, (uint32)0);
  Bios_Pwm_Set (HSO_2_M, (uint16)0, (uint32)0);
  Bios_Pwm_Set (HSO_3_M, (uint16)0, (uint32)0);
  Bios_Pwm_Set (HSO_4_M, (uint16)0, (uint32)0);
  Bios_Pwm_Set (HSO_5_M, (uint16)0, (uint32)0);
  Bios_Pwm_Set (HSO_6_M, (uint16)0, (uint32)0);
  Bios_Pwm_Set (HSO_7_M, (uint16)0, (uint32)0);
  Bios_Pwm_Set (HSO_8_M, (uint16)0, (uint32)0);
  Bios_Pwm_Set (HSO_9_M, (uint16)0, (uint32)0);
  Bios_Pwm_Set (HSO_10_M, (uint16)0, (uint32)0);
  Bios_Pwm_Set (HSO_11_M, (uint16)0, (uint32)0);
  Bios_Pwm_Set (HSO_12_M, (uint16)0, (uint32)0);
  Bios_Pwm_Set (HSO_13_M, (uint16)0, (uint32)0);
  Bios_Pwm_Set (HSO_14_M, (uint16)0, (uint32)0);
  Bios_Pwm_Set (HSO_15_M, (uint16)0, (uint32)0);
  Bios_Pwm_Set (HSO_16_M, (uint16)0, (uint32)0);

  {
    extern void BIOS_L9945_HBRIDGE_SET_H1(uint32_t, int16_t, uint8_t, uint8_t);
    BIOS_L9945_HBRIDGE_SET_H1((uint32_t)0, (int16_t)0, (uint8_t)0, (uint8_t)0);
  }

  {
    extern void BIOS_L9945_HBRIDGE_SET_H2(uint32_t, int16_t, uint8_t, uint8_t);
    BIOS_L9945_HBRIDGE_SET_H2((uint32_t)0, (int16_t)0, (uint8_t)0, (uint8_t)0);
  }

  {
    extern void Bios_L9945_Disable();
    Bios_L9945_Disable();
  }

  {
    tPinID pinID = PIN_A10;
    tGPDORegVal val = 0;
    Bios_Dio_SetGPDO(pinID, val);
  }
}

void App_Rtos_MC0TaskIdle (void)
{
  static boolean recordedReset = FALSE;
  extern void App_EE_WriteAsync(uint8 param);
  if (g_EEWrite_Requested == 1) {
    App_EE_WriteAsync(1);
    g_EEWrite_Requested = 0;
  }

  App_EE_WriteAsync(0);
  if (g_Reprogram_Requested) {
    extern tBiosFeePage0 Bios_Fee_Page0;
    uint8 writeBuffer[EEE_PAGE_SIZE] = { 0 };

    Bios_Fee_Page0.resetCause = BIOS_RC_BOOT_REQUEST;
    Bios_Fee_Page0.ResetHist[9] = Bios_Fee_Page0.ResetHist[8];
    Bios_Fee_Page0.ResetHist[8] = Bios_Fee_Page0.ResetHist[7];
    Bios_Fee_Page0.ResetHist[7] = Bios_Fee_Page0.ResetHist[6];
    Bios_Fee_Page0.ResetHist[6] = Bios_Fee_Page0.ResetHist[5];
    Bios_Fee_Page0.ResetHist[5] = Bios_Fee_Page0.ResetHist[4];
    Bios_Fee_Page0.ResetHist[4] = Bios_Fee_Page0.ResetHist[3];
    Bios_Fee_Page0.ResetHist[3] = Bios_Fee_Page0.ResetHist[2];
    Bios_Fee_Page0.ResetHist[2] = Bios_Fee_Page0.ResetHist[1];
    Bios_Fee_Page0.ResetHist[1] = Bios_Fee_Page0.ResetHist[0];
    Bios_Fee_Page0.ResetHist[0] = BIOS_RC_BOOT_REQUEST;
    Bios_Fee_Page0.resetTask = BIOS_RTOS_TASK_ASW0_IDLE;
    Bios_Fee_Page0.ResetTaskHist[9] = Bios_Fee_Page0.ResetHist[8];
    Bios_Fee_Page0.ResetTaskHist[8] = Bios_Fee_Page0.ResetHist[7];
    Bios_Fee_Page0.ResetTaskHist[7] = Bios_Fee_Page0.ResetHist[6];
    Bios_Fee_Page0.ResetTaskHist[6] = Bios_Fee_Page0.ResetHist[5];
    Bios_Fee_Page0.ResetTaskHist[5] = Bios_Fee_Page0.ResetHist[4];
    Bios_Fee_Page0.ResetTaskHist[4] = Bios_Fee_Page0.ResetHist[3];
    Bios_Fee_Page0.ResetTaskHist[3] = Bios_Fee_Page0.ResetHist[2];
    Bios_Fee_Page0.ResetTaskHist[2] = Bios_Fee_Page0.ResetHist[1];
    Bios_Fee_Page0.ResetTaskHist[1] = Bios_Fee_Page0.ResetHist[0];
    Bios_Fee_Page0.ResetTaskHist[0] = BIOS_RTOS_TASK_ASW0_IDLE;
    Bios_Fee_Page0.FirstStartFlag = 0x1;
    Bios_Fee_Page0.Fill = 0x0000;
    memcpy(&writeBuffer, &Bios_Fee_Page0, sizeof(tBiosFeePage0));
    Bios_Fee_WriteNvData(0, &writeBuffer, EEE_PAGE_SIZE);
    App_Disable_Power_Outputs();
    Bios_Mcu_TriggerReset();
  }

  if (g_Sleep_Requested) {
    extern tBiosFeePage0 Bios_Fee_Page0;
    if (!recordedReset) {
      uint8 writeBuffer[EEE_PAGE_SIZE] = { 0 };

      Bios_Fee_Page0.resetCause = BIOS_RC_POWER_OFF_RESET;
      Bios_Fee_Page0.ResetHist[9] = Bios_Fee_Page0.ResetHist[8];
      Bios_Fee_Page0.ResetHist[8] = Bios_Fee_Page0.ResetHist[7];
      Bios_Fee_Page0.ResetHist[7] = Bios_Fee_Page0.ResetHist[6];
      Bios_Fee_Page0.ResetHist[6] = Bios_Fee_Page0.ResetHist[5];
      Bios_Fee_Page0.ResetHist[5] = Bios_Fee_Page0.ResetHist[4];
      Bios_Fee_Page0.ResetHist[4] = Bios_Fee_Page0.ResetHist[3];
      Bios_Fee_Page0.ResetHist[3] = Bios_Fee_Page0.ResetHist[2];
      Bios_Fee_Page0.ResetHist[2] = Bios_Fee_Page0.ResetHist[1];
      Bios_Fee_Page0.ResetHist[1] = Bios_Fee_Page0.ResetHist[0];
      Bios_Fee_Page0.ResetHist[0] = BIOS_RC_POWER_OFF_RESET;
      Bios_Fee_Page0.resetTask = BIOS_RTOS_TASK_ASW0_IDLE;
      Bios_Fee_Page0.ResetTaskHist[9] = Bios_Fee_Page0.ResetHist[8];
      Bios_Fee_Page0.ResetTaskHist[8] = Bios_Fee_Page0.ResetHist[7];
      Bios_Fee_Page0.ResetTaskHist[7] = Bios_Fee_Page0.ResetHist[6];
      Bios_Fee_Page0.ResetTaskHist[6] = Bios_Fee_Page0.ResetHist[5];
      Bios_Fee_Page0.ResetTaskHist[5] = Bios_Fee_Page0.ResetHist[4];
      Bios_Fee_Page0.ResetTaskHist[4] = Bios_Fee_Page0.ResetHist[3];
      Bios_Fee_Page0.ResetTaskHist[3] = Bios_Fee_Page0.ResetHist[2];
      Bios_Fee_Page0.ResetTaskHist[2] = Bios_Fee_Page0.ResetHist[1];
      Bios_Fee_Page0.ResetTaskHist[1] = Bios_Fee_Page0.ResetHist[0];
      Bios_Fee_Page0.ResetTaskHist[0] = BIOS_RTOS_TASK_ASW0_IDLE;
      Bios_Fee_Page0.FirstStartFlag = 0x0;
      Bios_Fee_Page0.Fill = 0x0000;
      memcpy(&writeBuffer, &Bios_Fee_Page0, sizeof(tBiosFeePage0));
      Bios_Fee_WriteNvData(0, &writeBuffer, EEE_PAGE_SIZE);
      App_Disable_Power_Outputs();
      recordedReset = TRUE;
    }

    tDioLevel linWake = STD_HIGH;
    tDioLevel canWake = STD_HIGH;
    tDioLevel ethWake = STD_HIGH;

    /* Need to Put Wake Devices to Sleep */
    Bios_Rtos_WaitUs(1000);
    Bios_Dio_SetOutputLevel(LIN2_EN, STD_LOW);

    {
      extern Std_ReturnType Bios_Eth_SetTransceiverMode (tBiosEthNetIfDesc
        netIfDesc, tBiosEthTrcvMode mode);
      Bios_Eth_SetTransceiverMode (Bios_Eth_GetDefaultNetIf(),
        BIOS_ETH_TRCV_MODE_DOWN);
    }

    Bios_Can_Stop (BIOS_MCAN_5);
    Bios_CanTrcv_SetMode(BIOS_CANTRCV_TLE9255_IDX, BIOS_CANTRCV_SLEEP_MODE);
    Bios_Rtos_WaitUs(5000);
    Bios_Dio_GetInputLevel(ETH_INH, &ethWake);
    Bios_Dio_GetInputLevel(CAN_INH, &canWake);
    Bios_Dio_GetInputLevel(LIN_INH, &linWake);
    if (canWake == STD_LOW && ethWake == STD_LOW && linWake == STD_LOW) {
      Bios_Sbc_RequestLowPowerMode();
    } else if (linWake == STD_HIGH) {
      Bios_Dio_SetOutputLevel(LIN2_EN, STD_HIGH);
    } else if (canWake == STD_HIGH) {
      Bios_CanTrcv_ClearWUFlag(BIOS_CANTRCV_TLE9255_IDX);
    }
  }

  {
    if (!app_is_in_shutdown) {
      extern void App_Core0Idle(void);
      App_Core0Idle();
    }
  }
}

void App_Rtos_MC0Task1ms (void)
{
  if (!app_is_in_shutdown) {
  }
}

void App_Rtos_MC0TaskFgnd(void)
{
  if (!app_is_in_shutdown) {
    Timer_FGND_10MS_SensPower();
    Timer_Foreground();
    rcm112_stack_check_step();

    /* Get model outputs here */
  }

  Timed_Trigger_XCP();
}

void App_Rtos_MC0Task20ms(void)
{
  if (!app_is_in_shutdown) {
  }
}

void App_Rtos_MC0Task50ms (void)
{
  if (!app_is_in_shutdown) {
  }

  Timer_Background_50MS();
  Timer_Background_50MS_SBN1H();
}

void App_Rtos_MC0Task100ms(void)
{
  if (!app_is_in_shutdown) {
  }
}

void App_Rtos_MC0Task250ms(void)
{
  if (!app_is_in_shutdown) {
  }
}

void App_Rtos_MC0Task500ms(void)
{
  if (!app_is_in_shutdown) {
  }
}

void App_Rtos_MC0Task1000ms(void)
{
  if (!app_is_in_shutdown) {
  }
}

uint8_T NewEagle_SeedKey(uint8* seed, uint8* TstrKey, uint8 length)
{
  UNUSED(seed);
  UNUSED(TstrKey);
  UNUSED(length);
  return (0x00);
}

boolean_T NewEagle_PreCond (void)
{
  return (TRUE);
}
