/*****************************************************************************
   raptor_gen.h
   Generated By:
   Raptor 2023b_1.0.0 (9999_9999)
   Matlab (R2023a) 9.14

   Copyright (c) 2024 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Wed Mar 27 13:31:34 2024
 *****************************************************************************/

#ifndef RAPTOR_GEN_H
#define RAPTOR_GEN_H

/*****************************************************************************
   INCLUDES
 *****************************************************************************/
#include "interface.h"

/*****************************************************************************
   DEFINES (REQUIRED!)
 *****************************************************************************/
#ifndef UNUSED
#define UNUSED(x)                      (void)x
#endif                                 /* UNUSED */

#define NUM_MEMORY_BLOCKS_INCLUDED_IN_APPLICATION_CHECKSUM ( 1 )
#define MEMORY_BLOCK_START_ADDRESS_1   (0x01044000)
#define MEMORY_BLOCK_LENGTH_1          (0x57C000)
#define CODESTART0                     ((char*)(MEMORY_BLOCK_START_ADDRESS_1 ))
#define CODEEND0                       ((char*)(MEMORY_BLOCK_START_ADDRESS_1 + MEMORY_BLOCK_LENGTH_1 - 1))

extern uint8 app_is_in_shutdown;
extern tBiosFeePage0 Bios_Fee_Page0;
extern Std_ReturnType Module_Shutdown(boolean shutdownPower);
extern Std_ReturnType Module_BootRequest(void);

/* extern definitions of OEM processes*/
extern void App_Rtos_MC0Task1ms ( void );
extern void App_Rtos_MC0Task5ms ( void );
extern void App_Rtos_MC0Task10ms ( void );
extern void App_Rtos_MC0Task20ms ( void );
extern void App_Rtos_MC0Task50ms ( void );
extern void App_Rtos_MC0Task100ms ( void );
extern void App_Rtos_MC0Task250ms ( void );
extern void App_Rtos_MC0Task500ms ( void );
extern void App_Rtos_MC0Task1000ms ( void );
extern void App_Rtos_MC0TaskInt ( void );
extern void App_Rtos_MC0TaskIdle ( void );
extern void App_Rtos_MC1Task1ms ( void );
extern void App_Rtos_MC1Task10ms ( void );
extern void App_Rtos_MC1Task100ms ( void );
extern void App_Rtos_MC1TaskIdle ( void );

#endif
