/*****************************************************************************
   raptor_time.h
   Generated By:
   Raptor 2023b_1.0.0 (9999_9999)
   Matlab (R2023a) 9.14

   Copyright (c) 2024 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Wed Mar 27 13:31:34 2024
 *****************************************************************************/

#ifndef TIME_API_H_
#define TIME_API_H_
#include "Platform_Types.h"
#include "Rtos_api.h"

/*   Returns the time (number of ms) that has gone by since the framework was started. */
extern uint32 raptor_ticks(void);

/*   Returns the time (number of us) that has gone by since the software was started. Note that this count will rollover every 71.6 minutes. */
extern uint32 raptor_ticks_us(void);
extern uint32 raptor_GetDeltaTime_ms(uint32* last);
extern uint32 raptor_GetDeltaTime_us(uint32* last);
extern float GetTimeSingle(void);
extern uint64 GetUpTime(void);
extern double GetAbsTimeDouble(void);
extern float GetAbsTime(void);

#endif                                 /* TIME_API_H_ */
