/*****************************************************************************
   raptor_time.c
   Generated By:
   Raptor 2023b_1.0.0 (9999_9999)
   Matlab (R2023a) 9.14

   Copyright (c) 2024 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Wed Mar 27 13:31:34 2024
 *****************************************************************************/

#include "Platform_Types.h"
#include "Rtos_api.h"

uint64 GetUpTime(void);

/**************************************************************************
 * FUNCTION     : GetUpTime
 * PURPOSE      : Returns the time (us) the system has been running.
 *              :
 **************************************************************************/
uint64 GetUpTime()
{
  uint64 upTime1;
  uint64 upTime2;
  upTime1 = Bios_Rtos_GetLongTimer();
  upTime2 = Bios_Rtos_GetLongTimer();
  if (upTime2 >= upTime1) {
    return upTime2;
  } else {
    return upTime1;
  }
}

/****************************************************************************************************
 * FUNCTION     : raptor_ticks
 * PURPOSE      : Returns the time (number of ms) that has gone by since the software was started.
 *              :
 ****************************************************************************************************/
uint32 raptor_ticks(void)
{
  return GetUpTime()/1000;
}

/*****************************************************************************************************
 * FUNCTION     : raptor_ticks_us
 * PURPOSE      : Returns the time (number of us) that has gone by since the software was started.
 *              : Note that this count will roll over every 71.6 minutes.
 *****************************************************************************************************/
uint32 raptor_ticks_us( void )
{
  return Bios_Rtos_GetTicksUs();
}

/*****************************************************************************************************
 * FUNCTION     : GetTimeSingle
 * PURPOSE      : Returns the time in seconds that has gone by since the software was started.
 *              : Note that this uses the 64bit ticks counter value to calculate time.
 *****************************************************************************************************/
float32 GetTimeSingle( void )
{
  float32 time = GetUpTime()/1000000.0f;
  return time;
}

/******************************************************************************************************
 * FUNCTION     : raptor_GetDeltaTime_us
 * PURPOSE      : Returns the time (number of us) since last.
 *              :
 ******************************************************************************************************/
uint32 raptor_GetDeltaTime_us(uint32* last)
{
  uint32 current_ticks = raptor_ticks_us();
  uint32 delta = 0;
  if (*last > current_ticks) {
    delta = (0xffffffff - *last) + current_ticks + 1;
  } else {
    delta = current_ticks - *last;
  }

  *last = current_ticks;
  return delta;
}

/**************************************************************************
 * FUNCTION     : raptor_GetDeltaTime_ms
 * PURPOSE      : Returns the time (number of us) since last.
 *              :
 **************************************************************************/
uint32 raptor_GetDeltaTime_ms(uint32* last)
{
  uint32 current_ticks = raptor_ticks();
  uint32 delta = 0;

  /* Milliseconds will overflow every ~71.58 minutes */
  if (*last > current_ticks) {
    /* Max MS is max us/1000 */
    delta = (4294967U - *last) + current_ticks + 1;
  } else {
    delta = current_ticks - *last;
  }

  *last = current_ticks;
  return delta;
}

/**************************************************************************
 * FUNCTION     : GetAbsTime
 * PURPOSE      : Returns the time (s) the system has been running.
 *              :
 **************************************************************************/
float32 GetAbsTime()
{
  float32 time;
  uint64 ticks = GetUpTime();
  time = (float32)(ticks);
  time = time * .000001f;
  return time;
}
