/*****************************************************************************
   raptor_can_config.h
   Generated By:
   Raptor 2023b_1.0.0 (9999_9999)
   Matlab (R2023a) 9.14

   Copyright (c) 2024 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Wed Mar 27 13:31:34 2024
 *****************************************************************************/

#ifndef RAPTOR_CAN_CONFIG__H
#define RAPTOR_CAN_CONFIG__H
#define BIOS_MCAN_1_RXQUEUE_SIZE       (16U)                     /**< Value define for CAN1 RX queue size   */
#define BIOS_MCAN_1_TXQUEUE_SIZE       (20U)                     /**< Value define for CAN1 TX queue size   */
#define BIOS_MCAN_2_RXQUEUE_SIZE       (16U)                     /**< Value define for CAN2 RX queue size   */
#define BIOS_MCAN_2_TXQUEUE_SIZE       (16U)                     /**< Value define for CAN2 TX queue size   */
#define BIOS_MCAN_3_RXQUEUE_SIZE       (16U)                     /**< Value define for CAN3 RX queue size   */
#define BIOS_MCAN_3_TXQUEUE_SIZE       (16U)                     /**< Value define for CAN3 TX queue size   */
#define BIOS_MCAN_4_RXQUEUE_SIZE       (16U)                     /**< Value define for CAN4 RX queue size   */
#define BIOS_MCAN_4_TXQUEUE_SIZE       (16U)                     /**< Value define for CAN4 TX queue size   */
#define BIOS_MCAN_5_RXQUEUE_SIZE       (16U)                     /**< Value define for CAN5 RX queue size   */
#define BIOS_MCAN_5_TXQUEUE_SIZE       (16U)                     /**< Value define for CAN5 TX queue size   */
#endif                                 /* RAPTOR_CAN_CONFIG__H */
