/*****************************************************************************
   raptor_types.h
   Generated By:
   Raptor 2023b_1.0.0 (9999_9999)
   Matlab (R2023a) 9.14

   Copyright (c) 2024 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Wed Mar 27 13:31:34 2024
 *****************************************************************************/

#ifndef RAPTOR_TYPES_H
#define RAPTOR_TYPES_H
#include "rtwtypes.h"
#include "rcm112_stack_check_types.h"
#ifndef NULL
#define NULL                           (0)
#endif
#endif
