/*****************************************************************************
   sbc_config.c
   Generated By:
   Raptor 2023b_1.0.0 (9999_9999)
   Matlab (R2023a) 9.14

   Copyright (c) 2024 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Wed Mar 27 13:31:34 2024
 *****************************************************************************/

#include "sbc_fs8x.h"
#include "sbc_api.h"

typedef enum {
  BIOS_SBC_INIT_FS = 0,
  /**< Indicate the SBC in initialize state                                        */
  BIOS_SBC_RELEASE_FSLINE,
  /**< Indicate the SBC is in release fail safe line state                         */
  BIOS_SBC_RUNTIME,
  /**< Indicate the SBC is in runtime state                                        */
  BIOS_SBC_TOTAL_STATE
  /**< Total states of SBC                                                         */
} tBiosSbcState;

extern tBiosSbcState sbcState;
