/*****************************************************************************
   Sent_Cfg.c
   Generated By:
   Raptor 2023b_1.0.0 (9999_9999)
   Matlab (R2023a) 9.14

   Copyright (c) 2024 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Wed Mar 27 13:31:34 2024
 *****************************************************************************/

#include "SENT_Cfg.h"
#include "SENT_api.h"

// This configuration will turn off all SENT processing in the SDK
const tBiosSENTDriverConfig bios_SENT_Config = {
  .numOfChannelsConfig = 0,
  .channelConfig = NULL_PTR,
};
