/*****************************************************************************
   XCP_App_XCP1.c
   Generated By:
   Raptor 2023b_1.0.0 (9999_9999)
   Matlab (R2023a) 9.14

   Copyright (c) 2024 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Wed Mar 27 13:31:34 2024
 *****************************************************************************/

#include "rcm112_stack_check.h"
#include "rcm112_stack_check_private.h"
#include "raptor_time.h"
#include "data.h"

/* S-Function Block: <S3>/raptor_xcp_update */
uint32_T XCP1__XCP_TX_ID_RAM = 768U;
XcpCan_MsgObjId_t g_msgObjId_XCP1;

#define TIMESUB(A,B)                   ((A >= B) ? (A-B):(0xFFFFFFFF-B+1+A))
#if defined __cplusplus || defined _cplusplus

extern "C"
{
  extern void Xcp_CmdProcessor(void);

#endif

  extern void XcpCan_RxCallback(uint32_T, uint8_T, uint8_T*);
  extern void XcpApp_CanTransmit_XCP1( XcpCan_MsgObjId_t msgObjId, uint32_T
    msgId, uint8_T numBytes, Xcp_StatePtr8 pBytes );

#if defined __cplusplus || defined _cplusplus

}

#endif

void RxTrig_XCP_BC_XCP1(void)
{
  uint32_T id;
  uint8_T length;
  uint16_T age;
  uint8_T extended;
  uint8_T data[8];
  uint32_T id_temp;
  length = can_get_RxTrig_XCP_BC_XCP1(&age, &id, &extended, &data[0], 8);
  id_temp = 0x100;
  if (extended) {
    id_temp |= 0x80000000;
  }

  XcpCan_RxCallback(id_temp, length, &data[0]);
  Bios_Rtos_SuspendOSInterrupts();
  Xcp_CmdProcessor();
  Bios_Rtos_ResumeOSInterrupts();
}

void RxTrig_XCP_CMD_XCP1(void)
{
  uint32_T id;
  uint8_T length;
  uint16_T age;
  uint8_T extended;
  uint8_T data[8];
  uint32_T id_temp;
  length = can_get_RxTrig_XCP_CMD_XCP1(&age, &id, &extended, &data[0], 8);
  id_temp = 0x200;
  if (extended) {
    id_temp |= 0x80000000;
  }

  XcpCan_RxCallback(id_temp, length, &data[0]);
  Bios_Rtos_SuspendOSInterrupts();
  Xcp_CmdProcessor();
  Bios_Rtos_ResumeOSInterrupts();
}

void XcpApp_CanTransmit_XCP1( XcpCan_MsgObjId_t msgObjId, uint32_T msgId,
  uint8_T numBytes, Xcp_StatePtr8 pBytes )
{
  /* Tx_XCP_XCP1  ------      */
  uint32_T id = XCP1__XCP_TX_ID_RAM;   //msgId & 0x1fffffff;
  uint8_T length = numBytes;
  uint8_T extended = ((msgId & 0x80000000) > 0);
  uint8_T data[8];
  memcpy(&data[0], pBytes, numBytes);
  can_send_Tx_XCP_XCP1(id, extended, length, &data[0]);
  g_msgObjId_XCP1 = msgObjId;
  if (g_msgObjId_XCP1 != XCPCAN_INVALID_MSGOBJID) {
    XcpCan_TxCallback(g_msgObjId_XCP1);
  }

  g_msgObjId_XCP1 = msgObjId;
}

extern void can_init_rxIdRxTrig_XCP_CMD_XCP1(uint32_T, uint8_T);
extern void can_init_rxIdRxTrig_XCP_BC_XCP1(uint32_T, uint8_T);
void XCP1_XCP_CAN_PreStart(uint32_T bc_id, uint32_T rx_id, uint32_T tx_id)
{
  XCP1__XCP_TX_ID_RAM = tx_id;
  XCP_MSG_RX_ID = rx_id;               /* Rx Id Type is Standard */
  can_init_rxIdRxTrig_XCP_BC_XCP1(bc_id, 0);
  can_init_rxIdRxTrig_XCP_CMD_XCP1(rx_id, 0);
}

void Timed_Trigger_XCP(void)
{
  {
    /* DAQ LIST Rate : 5 ms */
    {
      Xcp_DoDaqForEvent(0);
    }
  }

  {
    /* DAQ LIST Rate : 10 ms */
    static uint32_T cnt_daq__10ms = 1;
    if (cnt_daq__10ms >= 2) {
      cnt_daq__10ms = 0;
      Xcp_DoDaqForEvent(1);
    }

    cnt_daq__10ms++;
  }

  {
    /* DAQ LIST Rate : 100 ms */
    static uint32_T cnt_daq__100ms = 2;
    if (cnt_daq__100ms >= 20) {
      cnt_daq__100ms = 0;
      Xcp_DoDaqForEvent(2);
    }

    cnt_daq__100ms++;
  }

  {
    /* DAQ LIST Rate : 500 ms */
    static uint32_T cnt_daq__500ms = 3;
    if (cnt_daq__500ms >= 100) {
      cnt_daq__500ms = 0;
      Xcp_DoDaqForEvent(3);
    }

    cnt_daq__500ms++;
  }

  {
    /* DAQ LIST Rate : 1000 ms */
    static uint32_T cnt_daq__1000ms = 4;
    if (cnt_daq__1000ms >= 200) {
      cnt_daq__1000ms = 0;
      Xcp_DoDaqForEvent(4);
    }

    cnt_daq__1000ms++;
  }

  Xcp_CmdProcessor();
}
